### ISSUE TITLE
Loss of colors

### ISSUE THREAD

**Issue by int-index** [emilaxelsson/trackit#4]
When running `cabal v2-build 2>&1` without `trackit`, I get a colorized error message:

![image](https://user-images.githubusercontent.com/4061728/51268522-5f586a80-19d1-11e9-9f11-a740b7e3ff95.png)

With `trackit`, it's all single-color:

![image](https://user-images.githubusercontent.com/4061728/51268557-77c88500-19d1-11e9-97be-247c68e695b6.png)

**Comment by emilaxelsson** [comment]
It should work if you add the GHC flag `-fdiagnostics-color=always`.

For example, this works for me and shows a colorized error:

```
trackit -c 'ghc -fdiagnostics-color=always -e "True + False" 2>&1'
```

**Comment by int-index** [comment]
Indeed, running `cabal v2-build --ghc-options -fdiagnostics-color=always 2>&1` worked.
